DOC_HEADER = 'Checks if the type of a variable or literal is {}.'
DOC_BODY = ('\n\n'
            'Parameters\n'
            '----------\n'
            'value\n'
            '    The literal or variable to check the type of.\n'
            'name : str, optional\n'
            '    Name of the variable to check the type of.\n'
            '    Defaults to None.\n'
            '\n'
            'Returns\n'
            '-------\n'
            'value\n'
            '    The `value` passed in.\n'
            '\n'
            'Attributes\n'
            '----------\n'
            'types : tuple(type)\n'
            '    The type(s) to check for.\n'
            '\n'
            'Methods\n'
            '-------\n'
            'o(callable) : CompositionOf\n'
            '    Daisy-chains the type checker to another `callable`,\n'
            '    returning the functional composition of both.\n'
            '\n'
            'Raises\n'
            '------\n'
            'WrongTypeError\n'
            '    If the type of the variable or literal is not among the\n'
            '    allowed types.\n'
            '\n'
            'See also\n'
            '--------\n'
            'Just, CompositionOf')
